### ISSUE TITLE
Phanpy is confused by posts from dispora

### ISSUE THREAD

**Issue by BurnerWah** [cheeaun/phanpy#140]
**Describe the bug**
- Which site: phanpy.social

**To Reproduce**
1. Find a post from a dispora instance (in this case `lemmy.ml`)
2. Open it
3. The post will now show as if it's quoting itself

**Expected behavior**
The post shouldn't show as if it's quoting itself

**Screenshots**
![image](https://github.com/cheeaun/phanpy/assets/10004812/7f8d07d5-56fd-4515-b499-0d7ba2872396)
![image](https://github.com/cheeaun/phanpy/assets/10004812/cdb0db5f-d446-42d2-a0a3-35edc673a8d8)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 113.01

**Additional context**
This looks weird

**Comment by BurnerWah** [comment]
Yep, it's fixed now. Thank you!

**Comment by wakest** [comment]
this is apparently not fixed 
<img width="676" alt="image" src="https://github.com/cheeaun/phanpy/assets/7890201/884a23b4-c956-4ad1-bbd5-fae7ff171bc6">, just came across this issue on this post https://lemmy.ml/post/9736352
