### ISSUE TITLE
Bug: Full resolution image fails to appear

### ISSUE THREAD

**Issue by lamnatos** [cheeaun/phanpy#158]
On Safari iOS, on almost 95% of the images I tap on, regardless of the image's instance, a low/normal appears for a split second, it tries to switch to the full resolution image but it ends up showing nothing. If I pinch to zoom on the blank view, the full-res image appears though. It feels like the full image *is* there, but the switch between them is not successful.

On Windows with Firefox, the switch between resolutions is also clearly visible, like an extremely fast, progressive load of the full-res image. It's still jarring but at least the switch is properly completed.

edit: here's a quick demo of the issue: https://share.icloud.com/photos/0cdL2MSn7OTFfiePpxAcFY4YQ

**Comment by cheeaun** [comment]
Should be fixed now on production (possibly need to reload), can check it out 🙏

**Comment by timbray** [comment]
I'm on production on Safari, doesn't seem to be fixed.  In fact I never started seeing it until last week.  Is there a way to do an extra-hard reload to make sure I have the latest phanpy?

**Comment by lamnatos** [comment]
I'm still seeing the issue, it's *much* rarer than before but when it happens, it's worse than before: I can't see the full image even if I zoom in/out. It looks like the the full image *is* loaded but is not visible and I can't get it to appear.

**Comment by timbray** [comment]
Still here, on almost every picture on Safari.  Working fine on Mac Chrome, though.  For complicated reasons I need to use Safari for most things so this is annoying.

**Comment by cheeaun** [comment]
@timbray is this happening for images in the timeline or in the full-page image modal (after tap on image)? Or both? Is it Safari desktop? 🙇‍♂️

**Comment by timbray** [comment]
Only in the full page. Desktop Safari on M2.

**Comment by lamnatos** [comment]
It looks like it's working now? I haven't seen the issue since yesterday I think. I've also noticed the swap between low/hi resolution images in a couple of cases, it worked quickly and without any issues.

**Comment by timbray** [comment]
Agreed, latest fix seems to be working, THANKS!
